esphome:
  name: test_sonoff_tx_t2eu2c
  platform: ESP8266
  board: esp01_1m

# Sonoff TX T2EU2C (wall switch)
# First flash: short pin ( https://github.com/arendst/Sonoff-Tasmota/issues/5918 ) of ESP with GND, used 3.3V FTDI
# Pinout: testing with similar product pinout seems compatible https://esphome.io/devices/sonoff_t1_uk_3gang_v1.1.html

wifi:
  ssid: !secret esphome_wifi_ssid
  password: !secret esphome_wifi_password

api:

logger:

ota:

sensor:
- platform: wifi_signal
  name: "Test TXswitch WiFi Signal"
  update_interval: 60s
- platform: uptime
  name: "Test TXswitch Uptime"
  
text_sensor:
- platform: version
  name: "Test TXswitch Firmware version"
    
binary_sensor:
- platform: gpio
  pin:
    number: GPIO0
    mode: INPUT_PULLUP
    inverted: True
  name: "Test TXswitch Touchpad 1"
  id: button
  on_press:
    then:
      # logic for cycling through movements: open->stop->close->stop->...
      - lambda: |
          if (id(my_cover).current_operation == COVER_OPERATION_IDLE) {
            // Cover is idle, if at one end change direction
            if (id(my_cover).position < 0.02) {
              id(my_cover).open();
            } else if (id(my_cover).position > 0.98) {
              id(my_cover).close();
            } else {
              // check last direction and either open or close cover.
              if (id(var_last_closing)) {
                id(my_cover).open();
              } else {
                id(my_cover).close();
              }
            }
          } else {
            // Cover is opening/closing, remember the direction.
            id(var_last_closing) = (id(my_cover).current_operation == COVER_OPERATION_CLOSING);
            
            // Stop it.
            id(my_cover).stop();
          }
#- platform: gpio
#  pin:
#    number: GPIO9
#    mode: INPUT_PULLUP
#    inverted: True
#  name: "Test TXswitch Touchpad 2"
#- platform: gpio
#  pin:
#    number: GPIO10
#    mode: INPUT_PULLUP
#    inverted: True
#    name: "Test TXswitch Touchpad 3"
#- platform: status
#  name: "Test TXswitch Status"

switch:
- platform: gpio
  name: "Test TXswitch Relay 1"
  pin: GPIO12
  interlock: &interlock [open_cover, close_cover]
  id: open_cover
- platform: gpio
  name: "Test TXswitch Relay 2"
  pin: GPIO5
  interlock: *interlock
  id: close_cover
#- platform: gpio
#  name: "Test TXswitch Relay 3"
#  pin: GPIO4


cover:
- platform: time_based
  name: "Screen3"
  id: my_cover
  open_action:
    - switch.turn_on: open_cover
  open_duration: 50s
  close_action:
    - switch.turn_on: close_cover
  close_duration: 50s
  # actually 45s would be more than enough for closing but lets keep it the same
  stop_action:
    - switch.turn_off: open_cover
    - switch.turn_off: close_cover

globals:
- id: var_last_closing
  type: bool
  restore_value: no
  initial_value: 'false'

output:
# Register the blue LED as a dimmable output ....
- platform: esp8266_pwm
  id: blue_led
  pin: GPIO13
  inverted: True

light:
# ... and then make a light out of it.
- platform: monochromatic
  name: "Test TXswitch Blue LED"
  output: blue_led